{
  "swagger": "2.0",
  "info": { "version": "1.0", "title": "BE_Laravel_8", "contact": {} },
  "host": "be-laravel.herokuapp.com",
  "basePath": "/api",
  "securityDefinitions": {},
  "schemes": ["https", "http"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "paths":
    {
      "/getData":
        {
          "get":
            {
              "summary": "fetch",
              "tags": ["Misc"],
              "operationId": "fetch",
              "deprecated": false,
              "produces": ["application/json"],
              "parameters":
                [
                  {
                    "name": "Authorization",
                    "in": "header",
                    "required": false,
                    "default": "Bearer {token}",
                    "type": "string",
                  },
                ],
              "responses": { "200": { "description": "", "headers": {} } },
            },
        },
      "/register":
        {
          "post":
            {
              "summary": "register",
              "tags": ["Misc"],
              "operationId": "register",
              "deprecated": false,
              "produces": ["application/json"],
              "consumes": ["application/x-www-form-urlencoded"],
              "parameters":
                [
                  {
                    "name": "name",
                    "in": "formData",
                    "required": true,
                    "type": "string",
                    "description": "",
                  },
                  {
                    "name": "email",
                    "in": "formData",
                    "required": true,
                    "type": "string",
                    "description": "",
                  },
                  {
                    "name": "status",
                    "in": "formData",
                    "required": true,
                    "type": "string",
                    "description": "",
                  },
                  {
                    "name": "password",
                    "in": "formData",
                    "required": true,
                    "type": "integer",
                    "format": "int32",
                    "description": "",
                  },
                ],
              "responses": { "200": { "description": "", "headers": {} } },
            },
        },
      "/destroy/2/delete":
        {
          "delete":
            {
              "summary": "destroy",
              "tags": ["Misc"],
              "operationId": "destroy",
              "deprecated": false,
              "produces": ["application/json"],
              "consumes": ["application/x-www-form-urlencoded"],
              "parameters":
                [
                  {
                    "name": "Authorization",
                    "in": "header",
                    "required": false,
                    "default": "Bearer {token}",
                    "type": "string",
                  },

                  {
                    "name": "name",
                    "in": "formData",
                    "required": true,
                    "type": "string",
                    "description": "",
                  },
                  {
                    "name": "email",
                    "in": "formData",
                    "required": true,
                    "type": "string",
                    "description": "",
                  },
                  {
                    "name": "status",
                    "in": "formData",
                    "required": true,
                    "type": "string",
                    "description": "",
                  },
                  {
                    "name": "password",
                    "in": "formData",
                    "required": true,
                    "type": "integer",
                    "format": "int32",
                    "description": "",
                  },
                ],
              "responses": { "200": { "description": "", "headers": {} } },
            },
        },
      "/updateProfile/2/update":
        {
          "put":
            {
              "summary": "update",
              "tags": ["Misc"],
              "operationId": "update",
              "deprecated": false,
              "produces": ["application/json"],
              "parameters":
                [
                  {
                    "name": "Authorization",
                    "in": "header",
                    "required": false,
                    "default": "Bearer {token}",
                    "type": "string",
                  },

                  {
                    "name": "Body",
                    "in": "body",
                    "required": true,
                    "description": "",
                    "schema": { "$ref": "#/definitions/updaterequest" },
                  },
                ],
              "responses": { "200": { "description": "", "headers": {} } },
            },
        },
      "/signin":
        {
          "post":
            {
              "summary": "login",
              "tags": ["Misc"],
              "operationId": "login",
              "deprecated": false,
              "produces": ["application/json"],
              "consumes": ["application/x-www-form-urlencoded"],
              "parameters":
                [
                  {
                    "name": "Authorization",
                    "in": "header",
                    "required": false,
                    "default": "Bearer {token}",
                    "type": "string",
                  },

                  {
                    "name": "email",
                    "in": "formData",
                    "required": true,
                    "type": "string",
                    "description": "",
                  },
                  {
                    "name": "password",
                    "in": "formData",
                    "required": true,
                    "type": "integer",
                    "format": "int32",
                    "description": "",
                  },
                ],
              "responses": { "200": { "description": "", "headers": {} } },
            },
        },
    },
  "definitions":
    {
      "updaterequest":
        {
          "title": "updaterequest",
          "example": { "name": "triono herawati", "status": "married" },
          "type": "object",
          "properties":
            { "name": { "type": "string" }, "status": { "type": "string" } },
          "required": ["name", "status"],
        },
    },
  "tags": [{ "name": "Misc", "description": "" }],
}
